name: Deploy to gh-pages
on:
  push:
    branches:
      - main
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: 18
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      - name: Checkout
        uses: actions/checkout@v2
      - name: Clean install dependencies
        run: npm ci
      - name: Build
        run: next build
      - name: Export
        run: next export
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./out
